### ISSUE TITLE
Confusions on Inconsistencies between the codes and the paper

### ISSUE THREAD

**Issue by JiaQiSJTU** [NJUNLP/CoP#2]
Hi, I found there are some inconsistencies between the codes and the paper, which one should I follow to get the zero-shot results shown in the paper:

1. in the paper it calculates the difference between probabilities (Eq.1), while in the codes it actually calculates the difference between the log of each probability (BaselineBartScorer.py). The ranking of these two cases won't be the same for some cases.
2. in the paper, it said that "We simply double the weights of entity tokens and pronoun tokens to help the model focus on the specific category." at the end of Sec. 3.3.  However, in the code of entity_loss.py, it only cares about the entities and use the max(span_score), and it didn't used for summary-level zero-shot.
3. By the way, are the results of "Ours" in Table 4 in the original paper representing "Ours Zero-Shot" in Table 2?

I'm not sure if I missed some details. Looking forward to your reply! Thanks a lot!

**Comment by Ricardokevins** [comment]
> Hi, I found there are some inconsistencies between the codes and the paper, which one should I follow to get the zero-shot results shown in the paper:
> 
> 1. in the paper it calculates the difference between probabilities (Eq.1), while in the codes it actually calculates the difference between the log of each probability (BaselineBartScorer.py). The ranking of these two cases won't be the same for some cases.
> 2. in the paper, it said that "We simply double the weights of entity tokens and pronoun tokens to help the model focus on the specific category." at the end of Sec. 3.3.  However, in the code of entity_loss.py, it only cares about the entities and use the max(span_score), and it didn't used for summary-level zero-shot.
> 3. By the way, are the results of "Ours" in Table 4 in the original paper representing "Ours Zero-Shot" in Table 2?
> 
> I'm not sure if I missed some details. Looking forward to your reply! Thanks a lot!

Hello, thank you for your attention to our work！
1. In fact we use the log probability. We will revise the statement in the next version of the paper.
2. We only use the simplest version of CoP for summary-level task. Sec. 3.3 is designed for Fine-grained Category Inconsistency.I am still organizing this part of code and will release it.  On the other hand,  pass_loss_Entity is used for token-level task and it's intuition can be seen here [comment](https://github.com/NJUNLP/CoP/blob/4b7a195bf1091ea4cc976cff75bc4c547c0012b1/utils/entity_loss.py#L36)
3. Yes, we use zero-shot CoP in Summary-Level Task, and we will revise the paper for better clarity.

**Comment by JiaQiSJTU** [comment]
Thanks a lot! I got some more problems during the re-implementation.😅
Taking qags dataset as an example, it originally labeled with yes/no by three reviewers for each sentence in the summary. How to get the final factualness score for each summary?

**Comment by Ricardokevins** [comment]
> Thanks a lot! I got some more problems during the re-implementation.😅 Taking qags dataset as an example, it originally labeled with yes/no by three reviewers for each sentence in the summary. How to get the final factualness score for each summary?

I follow the data preprocessing in bartscore. I think the results are obtained by averaging score.
And i have release the code for reproducing the summary-level task, you can directly use the script for the convenience and accuracy.

**Comment by JiaQiSJTU** [comment]
I can get totally the same results with the toy.json file. 
However, when I ran on QAGS with BartScore's released data, the pearson correlations(scipy.stats) on QAGSCNN and QAGSXSUM are only 0.6949247880326226 and  0.22943294065447212 respectively, lagging behind the numbers in Table 4.
Emm, is there anything wrong?

**Comment by Ricardokevins** [comment]
> I can get totally the same results with the toy.json file.

Maybe you can use the data and script in repo to compare the result.
Before commit, i get the exact experiment result as table4 in remote server.

**Comment by Ricardokevins** [comment]
> I can get totally the same results with the toy.json file. However, when I ran on QAGS with BartScore's released data, the pearson correlations(scipy.stats) on QAGSCNN and QAGSXSUM are only 0.6949247880326226 and 0.22943294065447212 respectively, lagging behind the numbers in Table 4. Emm, is there anything wrong?

The inference part is served as a convenient API to get various result (for example, inference will produce sentence and token-level results all at once), and the implementation is a little different, which may cause some performance difference.

Maybe you can use the data and reproduce.sh script in repo for more accuate reproduction. Before commit, i get the exact experiment result as table4 in remote server.

**Comment by Ricardokevins** [comment]
I just re-run the script and the result of QAGSXUM/QAGSCNN is 0.2663353914492119 and  0.7301704780047028

**Comment by JiaQiSJTU** [comment]
Thanks you! I got the same results finally😭！（the differences was caused by "Recapital" in inference.py)

**Comment by JiaQiSJTU** [comment]
Would it be convenient to share the FRANK dataset as well?🙏
